apiVersion: batch/v1
kind: Job
metadata:
  name: install-aura
  namespace: aura
spec:
  activeDeadlineSeconds: 6120
  backoffLimit: 10  
  template:
    spec:
      serviceAccountName: aura-job
      initContainers:
      - name: api-registry
        image: phx.ocir.io/oraclepaasmicroservices/aura/api-registry-install:0.2.1-SNAPSHOT
        command: ["sh", "-c", "install-chart"]
        env:
        - name: HELM_OPTS
          value: " --set apiserver.persistence.size=50Gi --set global.images.pullpolicy=Always --set global.images.pullPolicy=Always --set global.imagepullsecret=aura-install-job --set global.images.pullSecret=aura-install-job"
        imagePullPolicy: Always
      - name: observability-tools
        image: phx.ocir.io/oraclepaasmicroservices/aura/observability-tools-install:0.2.1-SNAPSHOT
        command: ["sh", "-c", "install-chart"]
        env:
        - name: HELM_OPTS
          value: " --set apiserver.persistence.size=50Gi --set global.images.pullpolicy=Always --set global.images.pullPolicy=Always --set global.imagepullsecret=aura-install-job --set global.images.pullSecret=aura-install-job"
        imagePullPolicy: Always
      containers:
      - name: installation-complete
        image: busybox
        command: ['sh', '-c', 'echo "Helm, Istio and Aura Installed"']
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
      imagePullSecrets: 
      - name: aura-install-job
