apiVersion: v1
kind: ServiceAccount
metadata:
  name: aura-job
  namespace: aura
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aura-job-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: aura-job
  namespace: aura
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: helm
subjects:
  - kind: ServiceAccount
    name: helm
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
# Needed on OCI cluster for registry TODO - fix in helm charts
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-system-anonymous
subjects:
  - kind: User
    name: system:anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
# Needed on OCI cluster for mock service TODO - fix in helm charts
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: add-on-cluster-admin-for-aura-default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: aura
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin